### ISSUE TITLE
Show User's Name on Home Page

### ISSUE THREAD

**Issue by NateSeymour** [InspiranzaDEV/zenenti#80]
# What needs to be done?
Add user's name to the homepage. This should be the name that they saved in the initial welcome screen.

# What should it look like?
![image](https://github.com/user-attachments/assets/6590bf2d-5b02-44d4-b9b4-af34c3a9b183)

# Dependencies
- Depends on #79

**Comment by heismyke** [comment]
Is this problem solved already ? i Would love solve this issue
